[package]
name = "ex_merge_sort"
version = "0.1.0"
authors = ["winebarrel <sugawara@winebarrel.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
